run:
  timeout: 5m

# all available settings of specific linters
linters-settings:
  # Disable goheader for now, we can introduce this later
  #  goheader:
  #    template-path: header.txt
  goimports:
    local-prefixes: github.com/os-observability/tempo-operator
  misspell:
    locale: US
  govet:
    disable-all: true
    enable:
      - fieldalignment

linters:
  enable:
    # Disable for now, we can introduce this later
    # - goheader
    - goimports
    - misspell
    - gosec
    - govet
    - exhaustive
    - godot
    - unparam
